version: "3.0"

services:
  api:
    container_name: "api"
    build:
      context: ./api
    volumes:
      - ./api:/Users/yu/Documents/sample_webapp/api
    ports:
      - 8080:8080
    
  frontend:
    container_name: "frontend"
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/Users/yu/Documents/sample_webapp/frontend
    ports:
      - 8501:8501
    depends_on:
      - api

